require 'rspec'
require_relative '../lib/factura'
require_relative '../lib/llamadas/b'
require_relative '../lib/llamadas/llamada_local'
require_relative '../lib/llamadas/llamada_nacional_o_internacional'
require_relative '../lib/horarios/raria'