require 'rspec'
require_relative '../lib/factura'
require_relative '../lib/facturadores/facturador'
require_relative '../lib/facturadores/facturador_local'
require_relative '../lib/facturadores/facturador_nacional'
require_relative '../lib/franja_horaria'
require_relative '../lib/llamada'